# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='object_detection',
  serialized_pb=_b('\n\rmessage.proto\x12\x10object_detection\"\xcd\x01\n\nDetections\x12\x34\n\x07objects\x18\x01 \x03(\x0b\x32#.object_detection.Detections.Object\x1a\x88\x01\n\x06Object\x12\r\n\x05\x63lass\x18\x01 \x02(\t\x12\x0f\n\x07x_pixel\x18\x02 \x02(\x02\x12\x0f\n\x07y_pixel\x18\x03 \x02(\x02\x12\x0f\n\x07z_pixel\x18\x04 \x02(\x02\x12\x0c\n\x04x_mm\x18\x05 \x02(\x02\x12\x0c\n\x04y_mm\x18\x06 \x02(\x02\x12\x0c\n\x04z_mm\x18\x07 \x02(\x02\x12\x12\n\nconfidence\x18\x08 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DETECTIONS_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='object_detection.Detections.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class', full_name='object_detection.Detections.Object.class', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_pixel', full_name='object_detection.Detections.Object.x_pixel', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_pixel', full_name='object_detection.Detections.Object.y_pixel', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z_pixel', full_name='object_detection.Detections.Object.z_pixel', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_mm', full_name='object_detection.Detections.Object.x_mm', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_mm', full_name='object_detection.Detections.Object.y_mm', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z_mm', full_name='object_detection.Detections.Object.z_mm', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='object_detection.Detections.Object.confidence', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=241,
)

_DETECTIONS = _descriptor.Descriptor(
  name='Detections',
  full_name='object_detection.Detections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objects', full_name='object_detection.Detections.objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DETECTIONS_OBJECT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=241,
)

_DETECTIONS_OBJECT.containing_type = _DETECTIONS
_DETECTIONS.fields_by_name['objects'].message_type = _DETECTIONS_OBJECT
DESCRIPTOR.message_types_by_name['Detections'] = _DETECTIONS

Detections = _reflection.GeneratedProtocolMessageType('Detections', (_message.Message,), dict(

  Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(
    DESCRIPTOR = _DETECTIONS_OBJECT,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:object_detection.Detections.Object)
    ))
  ,
  DESCRIPTOR = _DETECTIONS,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.Detections)
  ))
_sym_db.RegisterMessage(Detections)
_sym_db.RegisterMessage(Detections.Object)


# @@protoc_insertion_point(module_scope)
