// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace object_detection {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class Detections;
class Detections_Object;

// ===================================================================

class Detections_Object : public ::google::protobuf::Message {
 public:
  Detections_Object();
  virtual ~Detections_Object();

  Detections_Object(const Detections_Object& from);

  inline Detections_Object& operator=(const Detections_Object& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Detections_Object& default_instance();

  void Swap(Detections_Object* other);

  // implements Message ----------------------------------------------

  Detections_Object* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Detections_Object& from);
  void MergeFrom(const Detections_Object& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string class = 1;
  inline bool has_class_() const;
  inline void clear_class_();
  static const int kClassFieldNumber = 1;
  inline const ::std::string& class_() const;
  inline void set_class_(const ::std::string& value);
  inline void set_class_(const char* value);
  inline void set_class_(const char* value, size_t size);
  inline ::std::string* mutable_class_();
  inline ::std::string* release_class_();
  inline void set_allocated_class_(::std::string* class_);

  // required float x_pixel = 2;
  inline bool has_x_pixel() const;
  inline void clear_x_pixel();
  static const int kXPixelFieldNumber = 2;
  inline float x_pixel() const;
  inline void set_x_pixel(float value);

  // required float y_pixel = 3;
  inline bool has_y_pixel() const;
  inline void clear_y_pixel();
  static const int kYPixelFieldNumber = 3;
  inline float y_pixel() const;
  inline void set_y_pixel(float value);

  // required float z_pixel = 4;
  inline bool has_z_pixel() const;
  inline void clear_z_pixel();
  static const int kZPixelFieldNumber = 4;
  inline float z_pixel() const;
  inline void set_z_pixel(float value);

  // required float x_mm = 5;
  inline bool has_x_mm() const;
  inline void clear_x_mm();
  static const int kXMmFieldNumber = 5;
  inline float x_mm() const;
  inline void set_x_mm(float value);

  // required float y_mm = 6;
  inline bool has_y_mm() const;
  inline void clear_y_mm();
  static const int kYMmFieldNumber = 6;
  inline float y_mm() const;
  inline void set_y_mm(float value);

  // required float z_mm = 7;
  inline bool has_z_mm() const;
  inline void clear_z_mm();
  static const int kZMmFieldNumber = 7;
  inline float z_mm() const;
  inline void set_z_mm(float value);

  // @@protoc_insertion_point(class_scope:object_detection.Detections.Object)
 private:
  inline void set_has_class_();
  inline void clear_has_class_();
  inline void set_has_x_pixel();
  inline void clear_has_x_pixel();
  inline void set_has_y_pixel();
  inline void clear_has_y_pixel();
  inline void set_has_z_pixel();
  inline void clear_has_z_pixel();
  inline void set_has_x_mm();
  inline void clear_has_x_mm();
  inline void set_has_y_mm();
  inline void clear_has_y_mm();
  inline void set_has_z_mm();
  inline void clear_has_z_mm();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* class__;
  float x_pixel_;
  float y_pixel_;
  float z_pixel_;
  float x_mm_;
  float y_mm_;
  float z_mm_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Detections_Object* default_instance_;
};
// -------------------------------------------------------------------

class Detections : public ::google::protobuf::Message {
 public:
  Detections();
  virtual ~Detections();

  Detections(const Detections& from);

  inline Detections& operator=(const Detections& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Detections& default_instance();

  void Swap(Detections* other);

  // implements Message ----------------------------------------------

  Detections* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Detections& from);
  void MergeFrom(const Detections& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Detections_Object Object;

  // accessors -------------------------------------------------------

  // repeated .object_detection.Detections.Object objects = 1;
  inline int objects_size() const;
  inline void clear_objects();
  static const int kObjectsFieldNumber = 1;
  inline const ::object_detection::Detections_Object& objects(int index) const;
  inline ::object_detection::Detections_Object* mutable_objects(int index);
  inline ::object_detection::Detections_Object* add_objects();
  inline const ::google::protobuf::RepeatedPtrField< ::object_detection::Detections_Object >&
      objects() const;
  inline ::google::protobuf::RepeatedPtrField< ::object_detection::Detections_Object >*
      mutable_objects();

  // @@protoc_insertion_point(class_scope:object_detection.Detections)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::object_detection::Detections_Object > objects_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Detections* default_instance_;
};
// ===================================================================


// ===================================================================

// Detections_Object

// required string class = 1;
inline bool Detections_Object::has_class_() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Detections_Object::set_has_class_() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Detections_Object::clear_has_class_() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Detections_Object::clear_class_() {
  if (class__ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    class__->clear();
  }
  clear_has_class_();
}
inline const ::std::string& Detections_Object::class_() const {
  // @@protoc_insertion_point(field_get:object_detection.Detections.Object.class)
  return *class__;
}
inline void Detections_Object::set_class_(const ::std::string& value) {
  set_has_class_();
  if (class__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    class__ = new ::std::string;
  }
  class__->assign(value);
  // @@protoc_insertion_point(field_set:object_detection.Detections.Object.class)
}
inline void Detections_Object::set_class_(const char* value) {
  set_has_class_();
  if (class__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    class__ = new ::std::string;
  }
  class__->assign(value);
  // @@protoc_insertion_point(field_set_char:object_detection.Detections.Object.class)
}
inline void Detections_Object::set_class_(const char* value, size_t size) {
  set_has_class_();
  if (class__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    class__ = new ::std::string;
  }
  class__->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:object_detection.Detections.Object.class)
}
inline ::std::string* Detections_Object::mutable_class_() {
  set_has_class_();
  if (class__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    class__ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:object_detection.Detections.Object.class)
  return class__;
}
inline ::std::string* Detections_Object::release_class_() {
  clear_has_class_();
  if (class__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = class__;
    class__ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Detections_Object::set_allocated_class_(::std::string* class_) {
  if (class__ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete class__;
  }
  if (class_) {
    set_has_class_();
    class__ = class_;
  } else {
    clear_has_class_();
    class__ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:object_detection.Detections.Object.class)
}

// required float x_pixel = 2;
inline bool Detections_Object::has_x_pixel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Detections_Object::set_has_x_pixel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Detections_Object::clear_has_x_pixel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Detections_Object::clear_x_pixel() {
  x_pixel_ = 0;
  clear_has_x_pixel();
}
inline float Detections_Object::x_pixel() const {
  // @@protoc_insertion_point(field_get:object_detection.Detections.Object.x_pixel)
  return x_pixel_;
}
inline void Detections_Object::set_x_pixel(float value) {
  set_has_x_pixel();
  x_pixel_ = value;
  // @@protoc_insertion_point(field_set:object_detection.Detections.Object.x_pixel)
}

// required float y_pixel = 3;
inline bool Detections_Object::has_y_pixel() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Detections_Object::set_has_y_pixel() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Detections_Object::clear_has_y_pixel() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Detections_Object::clear_y_pixel() {
  y_pixel_ = 0;
  clear_has_y_pixel();
}
inline float Detections_Object::y_pixel() const {
  // @@protoc_insertion_point(field_get:object_detection.Detections.Object.y_pixel)
  return y_pixel_;
}
inline void Detections_Object::set_y_pixel(float value) {
  set_has_y_pixel();
  y_pixel_ = value;
  // @@protoc_insertion_point(field_set:object_detection.Detections.Object.y_pixel)
}

// required float z_pixel = 4;
inline bool Detections_Object::has_z_pixel() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Detections_Object::set_has_z_pixel() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Detections_Object::clear_has_z_pixel() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Detections_Object::clear_z_pixel() {
  z_pixel_ = 0;
  clear_has_z_pixel();
}
inline float Detections_Object::z_pixel() const {
  // @@protoc_insertion_point(field_get:object_detection.Detections.Object.z_pixel)
  return z_pixel_;
}
inline void Detections_Object::set_z_pixel(float value) {
  set_has_z_pixel();
  z_pixel_ = value;
  // @@protoc_insertion_point(field_set:object_detection.Detections.Object.z_pixel)
}

// required float x_mm = 5;
inline bool Detections_Object::has_x_mm() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Detections_Object::set_has_x_mm() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Detections_Object::clear_has_x_mm() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Detections_Object::clear_x_mm() {
  x_mm_ = 0;
  clear_has_x_mm();
}
inline float Detections_Object::x_mm() const {
  // @@protoc_insertion_point(field_get:object_detection.Detections.Object.x_mm)
  return x_mm_;
}
inline void Detections_Object::set_x_mm(float value) {
  set_has_x_mm();
  x_mm_ = value;
  // @@protoc_insertion_point(field_set:object_detection.Detections.Object.x_mm)
}

// required float y_mm = 6;
inline bool Detections_Object::has_y_mm() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Detections_Object::set_has_y_mm() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Detections_Object::clear_has_y_mm() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Detections_Object::clear_y_mm() {
  y_mm_ = 0;
  clear_has_y_mm();
}
inline float Detections_Object::y_mm() const {
  // @@protoc_insertion_point(field_get:object_detection.Detections.Object.y_mm)
  return y_mm_;
}
inline void Detections_Object::set_y_mm(float value) {
  set_has_y_mm();
  y_mm_ = value;
  // @@protoc_insertion_point(field_set:object_detection.Detections.Object.y_mm)
}

// required float z_mm = 7;
inline bool Detections_Object::has_z_mm() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Detections_Object::set_has_z_mm() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Detections_Object::clear_has_z_mm() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Detections_Object::clear_z_mm() {
  z_mm_ = 0;
  clear_has_z_mm();
}
inline float Detections_Object::z_mm() const {
  // @@protoc_insertion_point(field_get:object_detection.Detections.Object.z_mm)
  return z_mm_;
}
inline void Detections_Object::set_z_mm(float value) {
  set_has_z_mm();
  z_mm_ = value;
  // @@protoc_insertion_point(field_set:object_detection.Detections.Object.z_mm)
}

// -------------------------------------------------------------------

// Detections

// repeated .object_detection.Detections.Object objects = 1;
inline int Detections::objects_size() const {
  return objects_.size();
}
inline void Detections::clear_objects() {
  objects_.Clear();
}
inline const ::object_detection::Detections_Object& Detections::objects(int index) const {
  // @@protoc_insertion_point(field_get:object_detection.Detections.objects)
  return objects_.Get(index);
}
inline ::object_detection::Detections_Object* Detections::mutable_objects(int index) {
  // @@protoc_insertion_point(field_mutable:object_detection.Detections.objects)
  return objects_.Mutable(index);
}
inline ::object_detection::Detections_Object* Detections::add_objects() {
  // @@protoc_insertion_point(field_add:object_detection.Detections.objects)
  return objects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::object_detection::Detections_Object >&
Detections::objects() const {
  // @@protoc_insertion_point(field_list:object_detection.Detections.objects)
  return objects_;
}
inline ::google::protobuf::RepeatedPtrField< ::object_detection::Detections_Object >*
Detections::mutable_objects() {
  // @@protoc_insertion_point(field_mutable_list:object_detection.Detections.objects)
  return &objects_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace object_detection

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
